version: '3'
services:
    token-alert:
        build: .
        ports:
            - ${PORT:-3000}:${PORT:-3000}
        environment:
            - TM_RPC_IP=${TM_RPC_IP}
            - TM_RPC_PORT=${TM_RPC_PORT}
            - TOKEN_THRESHOLD_TO_ALERT=${TOKEN_THRESHOLD_TO_ALERT}
            - LINE_GROUP_TOKEN=${LINE_GROUP_TOKEN}
            - CRON_MINUTE=${CRON_MINUTE}
            - CRON_HOUR=${CRON_HOUR}
            - CRON_DAY_OF_MONTH=${CRON_DAY_OF_MONTH}
            - CRON_MONTH=${CRON_MONTH}
            - CRON_DAY_OF_WEEK=${CRON_DAY_OF_WEEK}
        restart: unless-stopped